version: "3.3"

services:
  expressapp:
    build: .
    image: sample-node-api
    container_name: sample-node-api
    restart: unless-stopped
    networks:
      - app-network
    # working_dir: /app
    # ports:
      # - "8080:8080"
    # volumes:
      # - ./:/app
    # command: sh -c "npm install && node src/index.js"

  proxy:
    image: nginx:alpine
    container_name: web-proxy
    restart: unless-stopped
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - expressapp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge